name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Generate lcov
        run: deno task coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Run benchmarks
        run: deno task bench