name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Install step
        run: deno task test

      - name: Build step
        run: deno coverage --html

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: r2d2-coverage
          entrypoint: jsr:@std/http/file-server
          root: coverage/html
