name: udd-update-dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
      
      - name: Update dependencies
        run: deno run -A https://deno.land/x/udd/main.ts --test "deno task test:dev" mod.ts

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(deps): update dependencies"
          commit-message: "chore(deps): Update dependencies"
          delete-branch: true